/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function minimizeOtherWindows(): void
export declare function hideOtherWindows(): void
export declare function showOtherWindows(): void
export declare function setCurrentWindowTopmostAggressive(): boolean
export declare function setCurrentWindowTopmostUltimate(): boolean
export declare function setCurrentWindowTopmostSuperUltimate(): boolean
export declare function stopSuperUltimateTopmost(): boolean
export declare function startTopmostMonitor(): boolean
export declare function stopTopmostMonitor(): boolean
export declare function setCurrentWindowTopmost(): boolean
export declare function removeCurrentWindowTopmost(): boolean
export declare function blockWordLookupPopups(): boolean
export declare function startAntiPopupMonitor(): boolean
export declare function stopAntiPopupMonitor(): boolean
export declare function startSuperAntiPopupMode(): boolean
